version: 2
updates:
  - package-ecosystem: "npm"
    directory: "examples/signaling-server-nodejs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directories:
      - ".github/workflows"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 15
